conj_set: ["and", "or", "nor", "but", "yet", "so", "for"]

regex:
  ip4: \b(?:\d{1,3}\.){3}\d{1,3}\b
  domain: \b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b
  ip6: \b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b
  ip_with_port: \b(?:\d{1,3}\.){3}\d{1,3}[#\d+]+\b
  path_unix: \/(?:[^\/]+\/)*[^\/]+\.[^\/]+
  path_win: [A-Za-z]:\\(?:[^\\/:*?'<>|\r\n]+\\)*[^\\/:*?'<>|\r\n]+

log_type:
  kv: ["audit", "process"]
  req: ["access"]
  gen: ["auth", "linux"]

POI:
  apache:
    audit: ["type", "timestamp", "acct", "exe", "res"]
    access: ["Src_IP", "Timestamp", "Parameters", "Status", "Actions"]
  sysdig: ["time", "proc", "pid", "event_type", "fd", "path"]

format:
  process:
    # for testing 
    sysdig: "<Date> <CPU> <Proc> \(<PID>\) <Dir> <Event_Type> <Args>"
    # correct one
    # sysdig: "<Evt_Num> <Date> <CPU> <Proc> \(<PID>\) <Dir> <Event_Type> <Args>"
