conj_set: ["and", "or", "nor", "but", "yet", "so", "for"]

regex:
  ip: r"\b(?:\d{1,3}\.){3}\d{1,3}\b"
  domain: r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b"

POI:
  apache:
    audit: ["type", "timestamp", "acct", "exe", "res"]
