conj_set: ["and", "or", "nor", "but", "yet", "so", "for"]

regex:
  ip4: r"\b(?:\d{1,3}\.){3}\d{1,3}\b"
  domain: r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b"
  ip6: \b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b
  ip_with_port: \b(?:\d{1,3}\.){3}\d{1,3}[#\d+]+\b

log_type:
  kv: ["audit"]
  req: ["access"]
  gen: ["auth"]

POI:
  apache:
    audit: ["type", "timestamp", "acct", "exe", "res"]
    access: ["Src_IP", "Timestamp", "Parameters", "Status", "Actions"]
